services:
    nginx_service:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - 8000:443
        depends_on:
            - mysql_service
            - php_service
        volumes_from:
            - php_service
        networks:
            - modulo_scout_network
    php_service:
        build:
            context: .
            dockerfile: php/Dockerfile
        volumes:
            - "$PWD/php:/app"
        stdin_open: true
        networks:
            - modulo_scout_network
    mysql_service:
        image: mysql:8-debian
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: modulo_scout
        networks:
            - modulo_scout_network
    nodejs_service:
        build:
            context: .
            dockerfile: node/Dockerfile
        stdin_open: true
        environment:
            - "CI=true"
        volumes:
            - "$PWD/node:/app"
        ports:
            - 3000:3000
        networks:
            - modulo_scout_network
    phpmyadmin_service:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql_service
        depends_on:
            - mysql_service
        networks:
            - modulo_scout_network
networks:
    modulo_scout_network:
        driver: bridge
